# Generated by Django 5.2.11 on 2026-02-17 20:18

import django.core.validators
import django.db.models.deletion
import integration_service.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=50, verbose_name='Código Cliente')),
                ('file', models.FileField(upload_to=integration_service.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls', 'txt'])], verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamaño (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de procesar'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('error', 'Error'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
            ],
            options={
                'verbose_name': 'Archivo de Cliente',
                'verbose_name_plural': 'Archivos de Clientes',
                'db_table': 'integration_client_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=50, unique=True, verbose_name='Código Cliente')),
                ('mapping_config', models.JSONField(verbose_name='Configuración de Mapeo')),
                ('validation_rules', models.JSONField(blank=True, null=True, verbose_name='Reglas de Validación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeo de Cliente',
                'verbose_name_plural': 'Mapeos de Clientes',
                'db_table': 'integration_client_mappings',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('processing_summary', 'Resumen de Procesamiento'), ('client_errors', 'Errores por Cliente'), ('daily_summary', 'Resumen Diario')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(verbose_name='Datos del Reporte')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'integration_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('DEBUG', 'Depuración')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Detalles Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integration_service.clientfile')),
            ],
            options={
                'verbose_name': 'Log de Procesamiento',
                'verbose_name_plural': 'Logs de Procesamiento',
                'db_table': 'integration_processing_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
