# Generated by Django 5.2.11 on 2026-02-26 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=50, unique=True, verbose_name='Código Cliente')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('column_mapping', models.JSONField(help_text="Mapeo de columnas Excel a campos de la API (ej: {'nombre_completo': 'nombre'})", verbose_name='Mapeo de Columnas')),
                ('column_order', models.JSONField(help_text='Orden en que aparecerán las columnas en el Excel', verbose_name='Orden de Columnas')),
                ('export_format', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV plano'), ('txt', 'Texto plano'), ('json', 'JSON')], default='xlsx', max_length=10, verbose_name='Formato de Exportación')),
                ('excel_config', models.JSONField(blank=True, default=dict, help_text='Configuración específica para Excel (headers, estilos, etc)', verbose_name='Configuración Excel')),
                ('default_filters', models.JSONField(blank=True, default=dict, help_text="Filtros que se aplican automáticamente (ej: {'id_clie': 3})", verbose_name='Filtros por Defecto')),
                ('transformations', models.JSONField(blank=True, default=dict, help_text="Reglas de transformación de datos (ej: {'ciudad': 'left_pad_5'})", verbose_name='Transformaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Exportación',
                'verbose_name_plural': 'Configuraciones de Exportación',
                'db_table': 'integration_export_configs',
                'ordering': ['client_code'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filters_used', models.JSONField(default=dict, verbose_name='Filtros Aplicados')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='Número de Registros')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='completed', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Exportación')),
                ('export_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='integration_service.exportconfig', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Historial de Exportación',
                'verbose_name_plural': 'Historial de Exportaciones',
                'db_table': 'integration_export_history',
                'ordering': ['-exported_at'],
            },
        ),
    ]
