# Generated by Django 5.2.11 on 2026-03-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0002_exportconfig_exporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='client_code',
            field=models.CharField(choices=[('CLIENTE_REMESA', 'CLIENTE_REMESA SERFINANZA')], default='CLIENTE_REMESA', max_length=50, verbose_name='Código Cliente'),
        ),
    ]
