# Generated by Django 5.2.11 on 2026-03-11 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0003_alter_clientfile_client_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContabilidadExportConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=50, unique=True, verbose_name='Código Cliente')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('report_name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('column_mapping', models.JSONField(default=dict, verbose_name='Mapeo de Columnas')),
                ('column_order', models.JSONField(default=list, verbose_name='Orden de Columnas')),
                ('export_format', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF')], default='xlsx', max_length=10, verbose_name='Formato de Exportación')),
                ('default_filters', models.JSONField(default=dict, help_text="Filtros que se aplican automáticamente (ej: {'id_clie': 17})", verbose_name='Filtros por Defecto')),
                ('transformations', models.JSONField(blank=True, default=dict, verbose_name='Transformaciones')),
                ('excel_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración Excel')),
                ('invoice_template', models.CharField(default='standard', max_length=100, verbose_name='Plantilla de Factura')),
                ('tax_rules', models.JSONField(blank=True, default=dict, verbose_name='Reglas de Impuestos')),
                ('billing_info', models.JSONField(blank=True, default=dict, verbose_name='Información de Facturación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración Exportación Contabilidad',
                'verbose_name_plural': 'Configuraciones Exportación Contabilidad',
                'ordering': ['client_code'],
            },
        ),
        migrations.CreateModel(
            name='ContabilidadExportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre Archivo')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta Archivo')),
                ('record_count', models.IntegerField(verbose_name='Cantidad Registros')),
                ('filters_used', models.JSONField(default=dict, verbose_name='Filtros Usados')),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='Exportado')),
                ('export_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad_exports', to='integration_service.contabilidadexportconfig')),
            ],
            options={
                'verbose_name': 'Historial Exportación Contabilidad',
                'verbose_name_plural': 'Historial Exportaciones Contabilidad',
                'ordering': ['-exported_at'],
            },
        ),
    ]
