# Generated by Django 5.2.11 on 2026-03-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0004_contabilidadexportconfig_contabilidadexporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabilidadexportconfig',
            name='default_filters',
            field=models.JSONField(blank=True, default=dict, help_text="Filtros que se aplican automáticamente (ej: {'id_clie': 17, 'motivo_operacion': 'Entregado', 'pub_date': '2024-01-01'})", verbose_name='Filtros por Defecto'),
        ),
        migrations.AlterField(
            model_name='contabilidadexportconfig',
            name='transformations',
            field=models.JSONField(blank=True, default=dict, help_text="Reglas de transformación de datos (ej: {'ciudad': 'left_pad_5'})", verbose_name='Transformaciones'),
        ),
    ]
