# Generated by Django 5.2.11 on 2026-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0005_alter_contabilidadexportconfig_default_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabilidadexportconfig',
            name='fecha_filtro',
            field=models.DateField(blank=True, help_text='Fecha para filtrado jerárquico en el admin (similar a fecha_estado)', null=True, verbose_name='Fecha para Filtro'),
        ),
    ]
