# Generated by Django 5.2.11 on 2026-03-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0006_contabilidadexportconfig_fecha_filtro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabilidadexportconfig',
            name='fecha_filtro',
        ),
    ]
