# Generated by Django 5.2.11 on 2026-03-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0007_remove_contabilidadexportconfig_fecha_filtro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabilidadexportconfig',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='Fecha de entrega para filtrado simple en el admin', null=True, verbose_name='Fecha de Entrega'),
        ),
    ]
