# Generated by Django 5.2.11 on 2026-03-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration_service', '0008_contabilidadexportconfig_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabilidadexportconfig',
            name='fecha_entrega',
        ),
    ]
